<?xml version="1.0" encoding="utf-8"?>
<Project>
	<Import Condition=" !Exists('Directory.Build.props.user') " Project="Directory.Build.props.default" />
	<Import Condition=" Exists('Directory.Build.props.user') " Project="Directory.Build.props.user" />

	<!--配置-->
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>disable</Nullable>
		<GamePlatforms>Steam</GamePlatforms>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<LangVersion>9.0</LangVersion>
		<OutputType>Library</OutputType>
		<FileAlignment>512</FileAlignment>
		<Deterministic>true</Deterministic>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\Debug\</OutputPath>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<OutputPath>bin\Release\</OutputPath>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<!-- 热重载 -->
	<PropertyGroup>
		<HotReloadAutoRestart>true</HotReloadAutoRestart>
	</PropertyGroup>
	<!-- Mod基础设置 -->
	<PropertyGroup>
		<APIVersion>2</APIVersion>
		<ModVersion Condition=" '$(ModVersion)' == '' ">1.0.0</ModVersion>
		<!-- VANILLA_ID, EXPANSION1_ID, DLC2_ID, DLC3_ID -->
		<!--
        <RequiredDlcIds></RequiredDlcIds>
        <ForbiddenDlcIds></ForbiddenDlcIds>
        -->
	</PropertyGroup>

	<!-- 游戏目录 -->
	<PropertyGroup Condition=" '$(GamePlatform)' == 'Steam' ">
		<GameFolder>$(GameFolderSteam)</GameFolder>
	</PropertyGroup>
	<PropertyGroup>
		<MSBuildTasksHelperDLL>$(ProjectDir)bin/MSBuildTasksHelper.dll</MSBuildTasksHelperDLL>
	</PropertyGroup>
	<ItemDefinitionGroup>
		<Reference Private="false" SpecificVersion="false" />
		<ProjectReference Private="false" />
		<PackageReference PrivateAssets="All" GeneratePathProperty="true" />
	</ItemDefinitionGroup>

	<!-- 其他 -->
	<ItemGroup>
		<Reference Include="Assembly-CSharp" HintPath="$(GameFolder)/Assembly-CSharp.dll" />
		<Reference Include="Assembly-CSharp-firstpass" HintPath="$(GameFolder)/Assembly-CSharp-firstpass.dll" />
	    <Reference Include="0Harmony" HintPath="$(GameFolder)/0Harmony.dll" />
		<Reference Include="Newtonsoft.Json" HintPath="$(GameFolder)/Newtonsoft.Json.dll" />
		<Reference Include="UnityEngine" HintPath="$(GameFolder)/UnityEngine.dll" />
		<Reference Include="UnityEngine.CoreModule" HintPath="$(GameFolder)/UnityEngine.CoreModule.dll" />
		<Reference Include="UnityEngine.ImageConversionModule" HintPath="$(GameFolder)/UnityEngine.ImageConversionModule.dll" />
		<Reference Include="UnityEngine.TextRenderingModule" HintPath="$(GameFolder)/UnityEngine.TextRenderingModule.dll" />
		<Reference Include="UnityEngine.UI" HintPath="$(GameFolder)/UnityEngine.UI.dll" />
		<Reference Include="UnityEngine.UIModule" HintPath="$(GameFolder)/UnityEngine.UIModule.dll" />
		<Reference Include="Unity.TextMeshPro" HintPath="$(GameFolder)/Unity.TextMeshPro.dll" />
		<Reference Include="FMODUnity" HintPath="$(GameFolder)/FMODUnity.dll" />
	</ItemGroup>
	<Target Name="UniversalDebugVariables"
        BeforeTargets="BeforeBuild;PrepareForBuild;InitializeBuildStatus"
		Condition=" '$(EnableBuildDebug)' != 'false' "> <!-- 可通过开关关闭调试 -->
		<Message Importance="high" Text="====ModName:$(Title)===" />
		<Message Importance="high" Text="====Description:$(Description)===" />
		<Message Importance="high" Text="====ModVersion:$(ModVersion)===" />
		<Message Importance="high" Text="====Platform:$(Platform)" />
		<Message Importance="high" Text="====GameFolderSteam:$(GameFolderSteam)" />
		<Message Importance="high" Text="====ModOutPutFolder:$(ModOutputFolderDebug)" />
	</Target>
	<!-- 署名 -->
	<PropertyGroup>
		<Author>priy0315</Author>
		<Company>priy0315 (https://github.com/TurboBinCN)</Company>
		<Product>priy0315's ONI Mods</Product>
		<Copyright>Copyright © priy0315 2025-$([System.DateTime]::Now.Year)</Copyright>
	</PropertyGroup>
</Project>