<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="anim\assets\scp049_2\" />
    <Folder Include="Codex\" />
    <Folder Include="Duplicants\" />
    <Folder Include="Incidents\" />
    <Folder Include="Patches\" />
    <Folder Include="Properties\" />
    <Folder Include="UI\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Directory.Build.props.user" />
  </ItemGroup>

</Project>
